FROM timothyjmiller/prisma-studio:latest

# WORKDIR /usr/app
# COPY ./ /usr/app

# RUN NODE_ENV=development npm i -g --save-dev prisma@latest 
# RUN NODE_ENV=development npm i -g prisma/client@latest ## currently throwing error

# EXPOSE 5555

# ENTRYPOINT ["/bin/sh", "prisma-introspect.sh"]